config/routes.rb
Rails.application.routes.draw do
  root 'home#top'
  devise_for :users, controllers: { registrations: 'users/registrations', sessions: 'users/sessions' }

  devise_scope :user do
    get 'guest_login', to: 'users/sessions#guest_login'
  end

  get 'home/index', to: 'home#index'
  
  resources :users
  resources :onsens do
    member do
      post 'save'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/onsen.rb
class Onsen < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def guest?
    email == 'guest@example.com'
  end

  has_many :onsens, dependent: :destroy
  has_many :saved_onsens, class_name: 'Onsen', foreign_key: 'saved_by_user_id'
  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  helper_method :guest_user?

  def after_sign_in_path_for(resource)
    home_index_path
  end

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  private

  def guest_user?
    current_user && current_user.guest?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def top
  end

  def index
    @onsens = Onsen.order(created_at: :desc)
    @page_title = "ホーム"
  end
end

app/controllers/onsens_controller.rb
class OnsensController < ApplicationController
  before_action :authenticate_user!

  def create
    @onsen = current_user.onsens.build(onsen_params)
    if @onsen.save
      redirect_to @onsen, notice: t('notices.onsen_created')
    else
      render :new
    end
  end

  def save
    @onsen = Onsen.find(params[:id])
    @onsen.saved_by_user_id = current_user.id
    if @onsen.save
      redirect_to @onsen, notice: t('notices.onsen_saved')
    else
      redirect_to @onsen, alert: t('alerts.onsen_save_failed')
    end
  end

  private

  def onsen_params
    params.require(:onsen).permit(:name, :description)
  end
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  def edit
    @page_title = "アカウント設定"
    super
  end

  def create
    super do |resource|
      if resource.persisted?
        flash[:notice] = t('devise.registrations.account_created')
      end
    end
  end

  def after_sign_up_path_for(resource)
    home_index_path
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  def guest_login
    guest_user = User.find_or_create_by!(email: 'guest@example.com') do |user|
      user.password = SecureRandom.urlsafe_base64
      user.name = 'ゲストユーザー'
    end
    sign_in guest_user

    redirect_to home_index_path, notice: t('devise.sessions.guest_logged_in')
  end

  def after_sign_in_path_for(resource)
    home_index_path
  end

  def after_sign_out_path_for(resource_or_scope)
    root_path
  end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @page_title = "マイページ"
  end

  def update
    @user = User.find(params[:id])

    if params[:user][:remove_avatar] == "1"
      @user.avatar.purge
    end

    if @user.update(params.require(:user).permit(:name, :avatar))
      redirect_to user_path(@user), notice: t('devise.registrations.account_updated')
    else
      render 'devise/registrations/edit'
    end
  end

  def destroy
    @user = current_user

    if @user.guest?
      redirect_to request.referer || root_path, alert: t('devise.registrations.guest_account_deletion_error')
      return
    end

    @user.onsens.destroy_all if @user.onsens.present?

    @user.destroy
    redirect_to root_path, notice: t('devise.registrations.account_deleted')
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :avatar, :password, :password_confirmation, :current_password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "温泉マッチング"
    if page_title.blank?
      base_title
    else
      "#{base_title} - #{page_title}"
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/onsens_helper.rb
module OnsensHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<div class="home-container">
  <main class="home-main">
    <div class="title">
      <h1 class="main-title">温泉マッチング</h1>
      <p class="sub-title">〜あなたの好みの温泉地を見つけましょう〜 <br> ※あなたが訪れた温泉地を投稿することもできます</p>
    </div>
    <div class="button-container">
      <a href="<%= new_onsen_path %>" class="btn btn-3d-circle btn-post-onsen">
        <span class="btn-3d-circle-content">
          <span class="btn-3d-circle-front">新しい温泉地を <br> 投稿する</span>
        </span>
        <span class="btn-3d-circle-back"><i class="fas fa-plus"></i></span>
      </a>        
      <a href="<%#= new_user_preference_path %>" class="btn btn-3d-circle btn-find-onsen">
        <span class="btn-3d-circle-content">
          <span class="btn-3d-circle-front">あなたにぴったりの <br> 温泉を見つける</span>
        </span>
        <span class="btn-3d-circle-back"><i class="fas fa-heart"></i></span>
      </a>     
      <a href="<%#= search_onsen_path %>" class="btn btn-3d-circle btn-search-onsen">
        <span class="btn-3d-circle-content">
          <span class="btn-3d-circle-front">温泉地を <br> 詳細検索する</span>
        </span>
        <span class="btn-3d-circle-back"><i class="fas fa-search"></i></span>
      </a>
    </div>
  </main>
  <h2>人気の温泉地</h2>
  <div>
    <% @onsens.each do |onsen| %>
      <div>
        <div>
          <img src="<%= onsen.image || 'default_image.jpg' %>" alt="<%= onsen.name %>" style="height: 200px; object-fit: cover;">
          <div>
            <h5><%= link_to onsen.name, onsen_path(onsen) %></h5>
            <p><%= truncate(onsen.description, length: 100) %></p>
            <a href="<%= onsen_path(onsen) %>">詳細を見る</a>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/home/top.html.erb
<div class="top-container">
  <section class="bg1">
    <div id="login-container">
      <h2>日本の温泉地</h2>
      <div class="search-container">
        <input type="text" placeholder="キーワードを入力..." class="search-input">
        <button class="search-button">🔍</button>
      </div>
      <div class="login-links">
        <a href="<%= new_user_registration_path %>" class="login-link">新規登録</a>
        <a href="<%= new_user_session_path %>" class="login-link">ログイン</a>
        <a href="<%= guest_login_path %>" class="login-link">ゲストログイン</a>
      </div>
    </div>
  </section>
</div>

app/views/layouts/_flash_messages.html.erb
<% if flash[:alert] %>
  <div class="alert alert-danger">
    <%= flash[:alert] %>
  </div>
<% end %>
<% if flash[:notice] %>
  <div class="alert alert-success">
    <%= flash[:notice] %>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="footer-content">
  <p class="footer-copyright">&copy; 2024 ri914. All Rights Reserved.</p>
  <p class="footer-description">温泉マッチングは、ユーザーが自分の好みに合った温泉地を見つけるためのマッチングサービスです。</p>
  <p class="footer-skills">使用技術: <span>Ruby on Rails, HTML, CSS, JavaScript, Bootstrap</span></p>
  <p class="footer-contact">お問い合わせ: <a href="mailto:issue914@gmail.com">issue914@gmail.com</a></p>    
  <div class="footer-social-media">
    <a href="https://github.com/ri914" target="_blank" class="social-icon"><i class="fab fa-github"></i></a>
  </div>
</div>

app/views/layouts/_head.html.erb
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

<title><%= full_title(@page_title) %></title>

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">
<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Reggae+One&family=Yuji+Mai&family=Yuji+Syuku&display=swap" rel="stylesheet">

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js" integrity="sha384-fbbOQedDUMZZ5KreZpsbe1LCZPVmfTnH7ois6mU1QK+m14rQ1l2bGBq41eYeM/fS" crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>

<%= javascript_include_tag 'application', 'data-turbo-track': 'reload' %>

app/views/layouts/_header.html.erb
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mx-auto">
          <li class="nav-item">
            <a class="nav-link active" href="<%= user_signed_in? ? home_index_path : root_path %>">
              <i class="fas fa-home"></i> ホーム
            </a>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <a class="nav-link" href="<%#= onsen_index_path %>">
                <i class="fas fa-globe"></i> 温泉地一覧
              </a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <% if current_user.email == 'guest@example.com' %>
                  <%= image_tag 'default_avatar.png', class: "nav-avatar" %>
                  ゲスト
                <% else %>
                  <% if current_user.avatar.attached? %>
                    <%= image_tag current_user.avatar, class: "nav-avatar" %>
                  <% else %>
                    <%= image_tag 'default_avatar.png', class: "nav-avatar" %>
                  <% end %>
                  <%= current_user.name %>
                <% end %>
              </a>
              <ul class="dropdown-menu" aria-labelledby="userDropdown">
                <li><a class="dropdown-item" href="<%= user_path(current_user) %>"><i class="fas fa-user-circle"></i> マイページ</a></li>
                <li><a class="dropdown-item" href="<%= edit_user_registration_path %>"><i class="fas fa-cog"></i> 設定</a></li>
                <li class="nav-item">
                  <%= form_with url: destroy_user_session_path, method: :delete, local: true do |form| %>
                    <button type="submit" class="dropdown-item d-flex align-items-center" onclick="return confirm('ログアウトしますか？');">
                      <i class="fas fa-sign-out-alt me-2"></i>
                      ログアウト
                    </button>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= form_with url: user_path(current_user), method: :delete, local: true do |form| %>
                    <button type="submit" class="dropdown-item d-flex align-items-center" onclick="return confirm('本当に退会しますか？');">
                      <i class="fas fa-user-slash me-2"></i>
                      退会
                    </button>
                  <% end %>
                </li>
              </ul>
            </li>
            <li class="nav-item">
              <form method="get" action="#" class="search_container">
                <input type="text" size="25" placeholder="キーワードを入力...">
                <input type="submit" value="&#xf002">
              </form>
            </li>
          <% else %>
            <li class="nav-item">
              <a class="nav-link" href="<%= new_user_registration_path %>"><i class="fas fa-user-plus"></i> 新規登録</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= new_user_session_path %>"><i class="fas fa-sign-in-alt"></i> ログイン</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= guest_login_path %>"><i class="fas fa-user-friends"></i> ゲストログイン</a>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

app/views/layouts/_nav.html.erb
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav mx-auto">
          <li class="nav-item">
            <a class="nav-link active" href="<%= user_signed_in? ? home_index_path : root_path %>">
              <i class="fas fa-home"></i> ホーム
            </a>
          </li>
          <% if user_signed_in? %>
            <li class="nav-item">
              <a class="nav-link" href="<%#= onsen_index_path %>">
                <i class="fas fa-globe"></i> 温泉地一覧
              </a>
            </li>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <% if current_user.email == 'guest@example.com' %>
                  <%= image_tag 'default_avatar.png', class: "nav-avatar" %>
                  ゲスト
                <% else %>
                  <% if current_user.avatar.attached? %>
                    <%= image_tag current_user.avatar, class: "nav-avatar" %>
                  <% else %>
                    <%= image_tag 'default_avatar.png', class: "nav-avatar" %>
                  <% end %>
                  <%= current_user.name %>
                <% end %>
              </a>
              <ul class="dropdown-menu" aria-labelledby="userDropdown">
                <li><a class="dropdown-item" href="<%= user_path(current_user) %>"><i class="fas fa-user-circle"></i> マイページ</a></li>
                <li><a class="dropdown-item" href="<%= edit_user_registration_path %>"><i class="fas fa-cog"></i> 設定</a></li>
                <li class="nav-item">
                  <%= form_with url: destroy_user_session_path, method: :delete, local: true do |form| %>
                    <button type="submit" class="dropdown-item d-flex align-items-center" onclick="return confirm('ログアウトしますか？');">
                      <i class="fas fa-sign-out-alt me-2"></i>
                      ログアウト
                    </button>
                  <% end %>
                </li>
                <li class="nav-item">
                  <%= form_with url: user_path(current_user), method: :delete, local: true do |form| %>
                    <button type="submit" class="dropdown-item d-flex align-items-center" onclick="return confirm('本当に退会しますか？');">
                      <i class="fas fa-user-slash me-2"></i>
                      退会
                    </button>
                  <% end %>
                </li>
              </ul>
            </li>
            <li class="nav-item">
              <form method="get" action="#" class="search_container">
                <input type="text" size="25" placeholder="キーワードを入力...">
                <input type="submit" value="&#xf002">
              </form>
            </li>
          <% else %>
            <li class="nav-item">
              <a class="nav-link" href="<%= new_user_registration_path %>"><i class="fas fa-user-plus"></i> 新規登録</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= new_user_session_path %>"><i class="fas fa-sign-in-alt"></i> ログイン</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="<%= guest_login_path %>"><i class="fas fa-user-friends"></i> ゲストログイン</a>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html lang="ja">
  <body>

    <%= render 'layouts/head' %>

    <%= render 'layouts/nav' %>
    
    <%= render 'layouts/flash_messages' %>
    
    <%= yield %>
    
    <footer class="footer">
      <%= render 'layouts/footer' %> 
    </footer>
  </body>
</html>

app/views/onsens/new.html.erb
<h1>温泉地の投稿</h1>

<%= form_with model: @onsen, local: true do |form| %>
  <% if @onsen.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@onsen.errors.count, "error") %> prohibited this onsen from being saved:</h2>
      <ul>
        <% @onsen.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_field :location %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="actions">
    <%= form.submit '投稿', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="settings-container">
  <div class="settings-main">
    <div class="profile-section">
      <h1>プロフィール</h1>
      <div class="avatar-container">
        <% if @user.avatar.attached? %>
          <%= image_tag @user.avatar, class: "current-avatar" %>
        <% else %>
          <%= image_tag 'default_avatar.png', class: "current-avatar", alt: "デフォルトアイコン" %>
        <% end %>
      </div>    
      <% if @user.errors.any? %>
        <div class="alert alert-danger">
          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>     
      <p>メールアドレス: <%= @user.email %></p>
      <p>パスワード: ******</p>
      <%= link_to '編集', edit_user_registration_path, class: "edit-link btn btn-primary" %>
    </div>
    <div class="onsens-section">
      <h1>お気に入りの温泉地</h1>
      <% if @user.saved_onsens.any? %>
        <ul class="mypage-ul">
          <% @user.saved_onsens.each do |onsen| %>
            <li class="mypage-li">
              <%= link_to onsen.name, onsen_path(onsen) %>
            </li>
          <% end %>
        </ul>
      <% else %>
        <p class="note">お気に入りの温泉地はありません。</p>
      <% end %>
    </div>
  </div>
</div>